pull_request_rules:
  - name: Automatic merge for PRs
    conditions:
      - check-success = verify
    actions:
      merge:
        method: merge
merge_protections_settings:
  reporting_method: check-runs
